-f /home/IC/xsc/gmec/pythonToolsForVerilog/sim/fifo_ctrTest/filelist_defines.f
-f /home/IC/xsc/gmec/pythonToolsForVerilog/sim/fifo_ctrTest/filelist_modules.f
-f /home/IC/xsc/gmec/pythonToolsForVerilog/sim/fifo_ctrTest/filelist_uvm.f
